#\u5E94\u7528\u540D\u79F0
spring.application.name=rule-service
spring.profiles.active=dev
spring.http.encoding.enabled=true
spring.http.encoding.charset=utf-8
spring.http.encoding.force=true
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8
#\u683C\u5F0F\u5316json\u8F93\u51FA
spring.jackson.serialization.indent-output=true
server.port=8080
server.context-path=/api
#\u662F\u5426\u5206\u914D\u7684\u76F4\u63A5\u5185\u5B58
server.undertow.direct-buffers=true
#mybatis-plus\u914D\u7F6E
mybatis-plus.mapper-locations=classpath*:com/zc/**/dao/mapper/*.xml
#mybatis-plus.type-aliases-package=com.sevenatour.**.dao
#\u4E3B\u952E\u7C7B\u578B  0:"\u6570\u636E\u5E93ID\u81EA\u589E", 1:"\u7528\u6237\u8F93\u5165ID",2:"\u5168\u5C40\u552F\u4E00ID (\u6570\u5B57\u7C7B\u578B\u552F\u4E00ID)", 3:"\u5168\u5C40\u552F\u4E00ID UUID";
mybatis-plus.global-config.id-type=2
#\u5B57\u6BB5\u7B56\u7565 0:"\u5FFD\u7565\u5224\u65AD",1:"\u975E NULL \u5224\u65AD"),2:"\u975E\u7A7A\u5224\u65AD"
mybatis-plus.global-config.field-strategy=2
#\u9A7C\u5CF0\u4E0B\u5212\u7EBF\u8F6C\u6362
mybatis-plus.global-config.db-column-underline=true
mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.configuration.cache-enabled=false
#\u6570\u636E\u5E93\u5927\u5199\u4E0B\u5212\u7EBF\u8F6C\u6362
#mybatis-plus.global-config.capital-mode=true
#\u5E8F\u5217\u63A5\u53E3\u5B9E\u73B0\u7C7B\u914D\u7F6E
#mybatis-plus.global-config.key-generator=com.sevenatour.xxxxx
#\u903B\u8F91\u5220\u9664\u914D\u7F6E
#mybatis-plus.global-config.logic-delete-value=0
#mybatis-plus.global-config.logic-not-delete-value=1
#\u81EA\u5B9A\u4E49\u586B\u5145\u7B56\u7565\u63A5\u53E3\u5B9E\u73B0
#mybatis-plus.global-config.meta-object-handler=com.sevenatour.xxxxx
#\u81EA\u5B9A\u4E49SQL\u6CE8\u5165\u5668
#mybatis-plus.global-config.sql-injector=com.sevenatour.xxxxx
# \u4EE5\u4E0B\u7684\u914D\u7F6E\u4F1A\u5F71\u54CDbuffer,\u8FD9\u4E9Bbuffer\u4F1A\u7528\u4E8E\u670D\u52A1\u5668\u8FDE\u63A5\u7684IO\u64CD\u4F5C,\u6709\u70B9\u7C7B\u4F3Cnetty\u7684\u6C60\u5316\u5185\u5B58\u7BA1\u7406
# \u6BCF\u5757buffer\u7684\u7A7A\u95F4\u5927\u5C0F,\u8D8A\u5C0F\u7684\u7A7A\u95F4\u88AB\u5229\u7528\u8D8A\u5145\u5206
server.undertow.buffer-size=1024
# \u6BCF\u4E2A\u533A\u5206\u914D\u7684buffer\u6570\u91CF , \u6240\u4EE5pool\u7684\u5927\u5C0F\u662Fbuffer-size * buffers-per-region
server.undertow.buffers-per-region=1024
#\u914D\u7F6Eswagger\u9700\u8981\u626B\u63CF\u9876\u7EA7\u5305\u540D
swagger.package=com.zc
#orika\u914D\u7F6E
orika.enabled=true
orika.use-builtin-converters=true
orika.use-auto-mapping=true
orika.map-nulls=true
orika.dump-state-on-exception=false
orika.favor-extension=false
orika.capture-field-context=false