#使用配置
spring:
  profiles:
    active: dev
server:
  #client端口，注册中心端口为7752
  port: 8080
eureka:
  #注册中心地址
  port: 8761
  instance:
    hostname: localhost
    appname: ${spring.application}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.port}/eureka/
#以下为公共配置
#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources

#开发环境配置
---
spring:
  profiles: dev
  application: melon-bigdata-client


#测试环境配置
---
spring:
  profiles: test
  application: melon-bigdata-client


#生产环境配置
---
spring:
  profiles: prod
  application: melon-bigdata-client





